# Generated by Django 2.1.7 on 2019-04-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190402_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
