# Generated by Django 2.1.7 on 2019-04-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(default='static/none.png', upload_to='static/produtos'),
        ),
    ]
