# Generated by Django 2.1.7 on 2019-04-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(default='produto/static/produtos/produtos/none.png', upload_to='produto/static/produtos/produtos'),
        ),
    ]
