# Generated by Django 2.1.7 on 2019-04-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20190403_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(default='produtos/none.png', upload_to='produtos/'),
        ),
    ]
