# Generated by Django 2.1.7 on 2019-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20190403_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataFinalizacao',
            field=models.DateField(blank=True),
        ),
    ]
