# Generated by Django 2.1.7 on 2019-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20190403_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
